# Generated by Django 5.1.1 on 2024-10-01 19:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_topic_rooms_host_message_rooms_topic"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rooms",
            options={"ordering": ["-updated", "-created"]},
        ),
        migrations.AddField(
            model_name="rooms",
            name="participants",
            field=models.ManyToManyField(
                blank=True, related_name="participants", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
